### ISSUE TITLE
Should desc-tex ship with revtex4.1?

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/desc-tex#31]
See subject. I don't know...

**Comment by abmantz** [comment]
What does this actually mean?

**Comment by sethdigel** [comment]
Thank you for asking.

**Comment by kadrlica** [comment]
It means that some of the class files (`aastex6.2.cls`) depend on revtex4.1. We currently don't ship that dependency.

**Comment by abmantz** [comment]
I'm a little fuzzy on what it means to ship something, but I don't imagine that bundling other software with this is a good idea. It isn't even strictly speaking a dependency of the *core* functionality, which is just the bib and acknowledgements files. It makes sense that the bibliography test would trigger every possible dependency, since it's supposed to show the bibliography formatted in every possible way (and uses the Note class). But users don't even need to be able to run the tests, frankly. And if someone was going to latex their paper in a form that uses aastex, then they need all the dependencies for that anyway, independent of desc-tex.

**Comment by abmantz** [comment]
That said, the macros test where the awk error is relevant would be a nice thing for people to be able to compile. If there's an easy fix for that, we should do it. Have you tried explicitly calling gawk rather than awk in the Makefile? It's hard to imagine what else could be going on.

**Comment by kadrlica** [comment]
Ok, though it seems reasonable (and actionable) to note some of this on the README. Specifically, that the style files may require additional dependencies.
